"""
Controlled vocabulary for the literature-discovery app.

This file keeps linguistics-specific vocabulary separate from app.py.
The goal is not to list every possible linguistic term, but to help the app:

1. reject overly broad one-word searches,
2. allow specialized one-word searches,
3. ignore relation words like "under" and "in",
4. recognize common linguistic phrases,
5. match related forms like pragmatics/pragmatic and ideophones/ideophone.
"""


# -----------------------------
# Very broad one-word searches
# -----------------------------
# These are too broad when used alone.
# Example: "syntax" should trigger "please provide more information."

BROAD_SINGLE_TERMS = {
    "syntax",
    "semantics",
    "phonology",
    "morphology",
    "linguistics",
    "language",
    "grammar",
    "discourse",
    "meaning",
    "words",
    "sentences",
    "speech",
    "communication",
    "acquisition",
    "variation",
    "typology",
    "sociolinguistics",
    "psycholinguistics",
    "phonetics",
}


# -----------------------------
# Stopwords / relation words
# -----------------------------
# These words help express the user's intended relation,
# but they should not count as keywords by themselves.
#
# Example:
# "Turkish ideophones under negation"
# should become:
# "turkish", "ideophones", "negation"
#
# not:
# "turkish", "ideophones", "under", "negation"

STOPWORDS = {
    "the",
    "and",
    "or",
    "of",
    "in",
    "on",
    "for",
    "to",
    "a",
    "an",
    "with",
    "by",
    "from",
    "about",
    "into",
    "across",
    "under",
    "over",
    "between",
    "among",
    "through",
    "during",
    "within",
    "without",
    "via",
    "toward",
    "towards",
    "against",
    "at",
    "as",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "this",
    "that",
    "these",
    "those",
    "it",
    "its",
    "their",
    "his",
    "her",
    "our",
    "your",
    "my",
    "how does",
    "how did",
    "how do",
    "what are",
    "what is",
    "what was",
    "what were",
    "where is",
    "where are",
    "how",
    "what",
    "where",
}


# -----------------------------
# Specialized one-word terms
# -----------------------------
# These are allowed as one-word searches.
# Example: "clitics" or "ideophones" should be allowed.

SPECIALIZED_LINGUISTIC_TERMS = {
    # Morphosyntax
    "accusative",
    "agreement",
    "alignment",
    "anaphor",
    "anaphora",
    "applicative",
    "aspect",
    "binding",
    "case",
    "causative",
    "clitic",
    "clitics",
    "control",
    "dative",
    "ellipsis",
    "ergative",
    "ergativity",
    "evidential",
    "evidentials",
    "focus",
    "genitive",
    "imperative",
    "island",
    "modality",
    "mood",
    "movement",
    "nominative",
    "passive",
    "polarity",
    "raising",
    "reciprocal",
    "reflexive",
    "scrambling",
    "sluicing",
    "tense",
    "topic",
    "valency",
    "voice",

    # Semantics and pragmatics
    "alternatives",
    "anaphora",
    "assertion",
    "conditional",
    "counterfactual",
    "definiteness",
    "deixis",
    "entailment",
    "exhaustivity",
    "implicature",
    "indexicality",
    "mirativity",
    "negation",
    "negative",
    "presupposition",
    "quantification",
    "scalarity",
    "scope",
    "specificity",
    "vagueness",

    # Phonology and phonetics
    "affricate",
    "allophone",
    "assimilation",
    "consonant",
    "deletion",
    "dissimilation",
    "epenthesis",
    "fortition",
    "gemination",
    "harmony",
    "intonation",
    "lenition",
    "nasalization",
    "palatalization",
    "prosody",
    "stress",
    "syllable",
    "tone",
    "vowel",

    # Morphology
    "affix",
    "affixation",
    "allomorph",
    "allomorphy",
    "circumfix",
    "compounding",
    "derivation",
    "infix",
    "inflection",
    "nominalization",
    "prefix",
    "reduplication",
    "suffix",
    "suppletion",
    "verbalization",

    # Lexical / typological / descriptive
    "classifier",
    "classifiers",
    "ideophone",
    "ideophones",
    "particle",
    "particles",
    "serial",
    "switch-reference",

    # Methods / experimental linguistics
    "acceptability",
    "elicitation",
    "judgment",
    "judgments",
    "corpus",
    "experiment",
    "production",
    "comprehension",
}

# -----------------------------
# Multi-word linguistic phrases
# -----------------------------
# These can help future versions of the app recognize phrase-level topics.
# Users do not need quotation marks, but these are useful as a vocabulary list.

KNOWN_COLLOCATIONS = {
    "discourse particle",
    "event structure",
    "focus particle",
    "information structure",
    "modal concord",
    "scope ambiguity",
    "semantic scope",
    "argument structure",
    "case marking",
    "complement clause",
    "differential object marking",
    "long distance dependency",
    "negative concord",
    "negative polarity item",
    "object agreement",
    "positive polarity item",
    "relative clause",
    "serial verb construction",
    "subject agreement",
    "switch reference",
    "wh-movement",
    "wh-question",
    "wh movement",
    "wh question",
    "speech act",
    "stress assignment",
    "tone sandhi",
    "vowel harmony",
    "agreement marker",
    "nominal classification",
    "bare nouns",
    "bare noun",
    "negative polarity items",
    "negative polarity item",
    "polarity items",
    "polarity item",
    "positive polarity items",
    "positive polarity item",
    "focus particles",
    "focus particle",
    "scalar implicature",
    "scalar implicatures",
    "free choice",
    "free choice items",
    "free choice item",
    "word order",
    "case marking",
    "case markers",
    "case marker",
    "differential object marking",
    "object marking",
    "information structure",
    "discourse particles",
    "discourse particle",
    "speech acts",
    "speech act",
    "relative clauses",
    "relative clause",
    "wh questions",
    "wh question",
    "yes no questions",
    "yes no question",
    "polar questions",
    "polar question",
    "root clauses",
    "root clause",
    "embedded clauses",
    "embedded clause",
    "main clauses",
    "main clause",
    "manner adverbs",
    "manner adverb",
    "manner adverbials",
    "manner adverbial",
    "time adverbs",
    "time adverb",
    "time adverbials",
    "time adverbial",
    "degree modifiers",
    "degree modifier",
    "verbal morphology",
    "nominal morphology",
    "argument structure",
    "event structure",
    "predicate modification",
    "scope ambiguity",
    "scope interaction",
    "scope taking",
    "language acquisition",
    "first language acquisition",
    "second language acquisition",
    "heritage language",
    "heritage languages",
    "heritage speakers",
    "heritage speaker",
    "bilingual acquisition",
    "code switching",
    "code-switching",
    "agreement attraction",
    "island effects",
    "island effect",
    "quantifier scope",
    "scope of negation",
    "negative concord",
    "double negation",
    "sentential negation",
    "constituent negation",
    "nominal phrases",
    "nominal phrase",
    "noun phrases",
    "noun phrase",
    "verb phrases",
    "verb phrase",
    "prepositional phrases",
    "prepositional phrase",
    "determiner phrases",
    "determiner phrase",
    "definite descriptions",
    "definite description",
    "indefinite descriptions",
    "indefinite description",
    "bare plurals",
    "bare plural",
    "bare singulars",
    "bare singular",
    "mass nouns",
    "mass noun",
    "count nouns",
    "count noun",
    "generic readings",
    "generic reading",
    "existential readings",
    "existential reading",
    "specificity effects",
    "specificity effect",
    "referentiality effects",
    "referentiality effect",
    "presupposition projection",
    "exhaustivity effects",
    "exhaustivity effect",
    "focus sensitivity",
    "focus sensitive particles",
    "focus sensitive particle",
    "alternative semantics",
    "question under discussion",
    "questions under discussion",
    "discourse structure",
    "anaphoric dependency",
    "anaphoric dependencies",
    "long distance dependency",
    "long distance dependencies",
    "wh movement",
    "head movement",
    "verb movement",
    "scrambling effects",
    "scrambling effect",
    "null subjects",
    "null subject",
    "pro drop",
    "pro-drop",
    "subject drop",
    "object drop",
    "sluicing",
    "ellipsis resolution",
    "verb phrase ellipsis",
    "vp ellipsis",
    "gapping",
    "right node raising",
    "control structures",
    "control structure",
    "raising verbs",
    "raising verb",
    "modal verbs",
    "modal verb",
    "auxiliary verbs",
    "auxiliary verb",
    "evidential markers",
    "evidential marker",
    "evidentiality markers",
    "evidentiality marker",
    "tense aspect",
    "tense and aspect",
    "aspectual markers",
    "aspectual marker",
    "perfective aspect",
    "imperfective aspect",
    "progressive aspect",
    "resultative constructions",
    "resultative construction",
    "causative constructions",
    "causative construction",
    "applicative constructions",
    "applicative construction",
    "passive constructions",
    "passive construction",
    "middle voice",
    "reflexive pronouns",
    "reflexive pronoun",
    "reciprocal pronouns",
    "reciprocal pronoun",
    "personal pronouns",
    "personal pronoun",
    "indexical expressions",
    "indexical expression",
    "deictic expressions",
    "deictic expression",
    "demonstrative pronouns",
    "demonstrative pronoun",
    "ideophonic expressions",
    "ideophonic expression",
    "sound symbolism",
    "iconic language",
    "iconic gesture",
    "gesture speech",
    "gesture and speech",
}


# -----------------------------
# Variant mappings
# -----------------------------
# These are hand-coded equivalences or near-equivalences that simple
# singular/plural matching may miss.
#
# The app can use this to match:
# "pragmatics" with "pragmatic"
# "negation" with "negative"
# "ideophones" with "ideophone"

TERM_VARIANTS = {
    "pragmatics": {"pragmatic"},
    "pragmatic": {"pragmatics"},

    "semantics": {"semantic"},
    "semantic": {"semantics"},

    "phonetics": {"phonetic"},
    "phonetic": {"phonetics"},

    "negation": {"negative", "negated"},
    "negative": {"negation", "negated"},
    "negated": {"negation", "negative"},

    "ideophone": {"ideophones", "ideophonic"},
    "ideophones": {"ideophone", "ideophonic"},
    "ideophonic": {"ideophone", "ideophones"},

    "clitic": {"clitics"},
    "clitics": {"clitic"},

    "evidential": {"evidentials", "evidentiality"},
    "evidentials": {"evidential", "evidentiality"},
    "evidentiality": {"evidential", "evidentials"},

    "presupposition": {"presuppositional"},
    "presuppositional": {"presupposition"},

    "implicature": {"implicatures"},
    "implicatures": {"implicature"},

    "morphology": {"morphological"},
    "morphological": {"morphology"},

    "phonology": {"phonological"},
    "phonological": {"phonology"},

    "typology": {"typological"},
    "typological": {"typology"},

    "turkish": {"turkic"},
    "turkic": {"turkish"},
}

LINGUISTIC_DOMAIN_TERMS = {
    "linguistic",
    "linguistics",
    "language",
    "languages",
    "grammar",
    "grammatical",
    "syntax",
    "syntactic",
    "semantics",
    "semantic",
    "pragmatics",
    "pragmatic",
    "phonology",
    "phonological",
    "phonetics",
    "phonetic",
    "morphology",
    "morphological",
    "morpheme",
    "morphemes",
    "word",
    "words",
    "lexical",
    "lexicon",
    "inflection",
    "inflectional",
    "derivation",
    "derivational",
    "stem",
    "stems",
    "root",
    "roots",
    "affix",
    "affixes",
    "suffix",
    "suffixes",
    "prefix",
    "prefixes",
    "clitic",
    "clitics",
    "case",
    "agreement",
    "tense",
    "aspect",
    "modality",
    "negation",
    "polarity",
    "focus",
    "topic",
    "discourse",
    "utterance",
    "speaker",
    "speakers",
    "Turkish",
    "English",
    "German",
    "Japanese",
    "Korean",
    "Arabic",
    "Hebrew",
    "Spanish",
    "French",
    "Italian",
    "Russian",
    "Mandarin",
    "Chinese",
}
